-- ============================================================
-- SECT — Paramètres PostgreSQL d'observabilité (audit DB)
-- ============================================================
--
-- 1. statement_timeout = 30000 (30s)
--    Timeout global au niveau DB. Filet de sécurité : une requête qui
--    dure plus de 30s est automatiquement annulée, libérant la
--    connexion PgBouncer (limite 60 connexions sur Supabase).
--
--    Valeur par défaut Supabase : 120000ms (2 min) — trop élevé pour
--    une API web. Une requête bloquée 2min consomme une connexion
--    précieuse et peut cascader en saturation du pool.
--
--    Ce paramètre est `USER` (modifiable par tout rôle) → accessible
--    via ALTER DATABASE avec le rôle postgres du pooler.
--
-- 2. log_min_duration_statement = 500 (NON inclus ici)
--    Paramètre SUSET (superuser-only) sur Supabase — non modifiable
--    via SQL avec le rôle postgres du pooler (permission denied).
--    À configurer manuellement via :
--      Dashboard Supabase → Database → Settings → Query logging
--    ou Supabase CLI : supabase --workdir . config set
--      db.log_min_duration_statement=500
--
--    Log toute requête > 500ms → détecter N+1 et plans dégradés.
--
-- Note : ALTER DATABASE ... SET persiste pour toutes les connexions
-- futures (niveau DATABASE, pas SESSION). Les connexions existantes
-- doivent se reconnecter pour hériter du nouveau paramètre.
-- ============================================================

ALTER DATABASE postgres SET statement_timeout = 30000;
